name: __NAME__

github:
  # https://docs.github.com/en/github/searching-for-information-on-github/searching-for-repositories
  #    all modules
  #    repo_search: "org:cloudposse"
  #    terraform modules
  repository_search: "repo:cloudposse/terraform-aws-sns-topic"

  branch: auto-__NAME__
  commit_message: auto-__NAME__
  pr:
    body: |
      ## what
      - what
      ## why:
      - why
    reviewers:
    - cloudpossebot
    team_reviewers:
    - terraform

    labels:
      - auto-approve
      - auto-merge

tests: true

migrations:
  - make init
  - make readme
